# Generated by Django 4.1.2 on 2023-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='content',
            field=models.TextField(default='none', verbose_name='Zawartość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='title',
            field=models.CharField(default='none', max_length=50, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
