# Generated by Django 4.1.2 on 2023-02-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_element_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
